//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCIProject.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ID_student { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> Stream_ID { get; set; }
        public Nullable<int> Supervisor_ID { get; set; }
    }
}
