//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCIProject.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FILE()
        {
            this.TBL_SUBMISSION = new HashSet<TBL_SUBMISSION>();
        }
    
        public int File_ID { get; set; }
        public string Filename { get; set; }
        public Nullable<bool> Content { get; set; }
        public byte[] Content_Type { get; set; }
        public Nullable<int> Submission_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> FileType { get; set; }
        public virtual TBL_FileType TBL_FileType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SUBMISSION> TBL_SUBMISSION { get; set; }
    }
}
