//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCIProject.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AspNetRole
    {
        public int Id_Role { get; set; }
        public Nullable<int> Name { get; set; }
    }
}
