//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCIProject.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SUBMISSIONDETAILS
    {
        public int SubmissionDetails_ID { get; set; }
        public Nullable<int> ID_Submission { get; set; }
        public Nullable<int> ID_tech { get; set; }
    
        public virtual TBL_SUBMISSION TBL_SUBMISSION { get; set; }
        public virtual TBL_TECHNOLOGIE TBL_TECHNOLOGIE { get; set; }
    }
}
